In [1]:
import pandas as pd 
import numpy as np

In [4]:
ds = pd.read_csv('tested.csv')
ds.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [6]:
ds.isnull().count

<bound method DataFrame.count of      PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False
1          False     False   False  False  False  False  False  False   False
2          False     False   False  False  False  False  False  False   False
3          False     False   False  False  False  False  False  False   False
4          False     False   False  False  False  False  False  False   False
..           ...       ...     ...    ...    ...    ...    ...    ...     ...
413        False     False   False  False  False   True  False  False   False
414        False     False   False  False  False  False  False  False   False
415        False     False   False  False  False  False  False  False   False
416        False     False   False  False  False   True  False  False   False
417        False     False   False  False  False   True  False  False   False

      Fare  Cabin  Embarked
0    False   True     False
1    False   True     False
2    False   True     False
3    False   True     False
4    False   True     False
..     ...    ...       ...
413  False   True     False
414  False  False     False
415  False   True     False
416  False   True     False
417  False   True     False

[418 rows x 12 columns]>

In [9]:
ds_drop = ds.dropna()
ds_drop

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,B45,S
14,906,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S
24,916,1,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
26,918,1,1,"Ostby, Miss. Helene Ragnhild",female,22.0,0,1,113509,61.9792,B36,C
28,920,0,1,"Brady, Mr. John Bertram",male,41.0,0,0,113054,30.5000,A21,S
...,...,...,...,...,...,...,...,...,...,...,...,...
404,1296,0,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,D40,C
405,1297,0,2,"Nourney, Mr. Alfred (Baron von Drachstedt"")""",male,20.0,0,0,SC/PARIS 2166,13.8625,D38,C
407,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
411,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

In [11]:
ds.shape

(418, 12)

In [12]:
ds_drop.shape

(87, 12)

In [13]:
ds_fill = ds.copy()

ds_fill["Age"] = ds_fill["Age"].fillna(ds_fill["Age"].mean())
ds_fill["Embarked"] = ds_fill["Embarked"].fillna(ds_fill["Embarked"].mode()[0])

print("Shape after fillna():", ds_fill.shape)

Shape after fillna(): (418, 12)

In [14]:
ds_fill["Pclass"] = ds_fill["Pclass"].astype(str)

In [15]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

ds_fill["Pclass"] = le.fit_transform(ds_fill["Pclass"])

In [16]:
ds_encoded = pd.get_dummies(
    ds_fill,
    columns=["Sex", "Embarked"],
    drop_first=True
)

In [17]:
print(ds_encoded.select_dtypes(include="object").columns)

Index(['Name', 'Ticket', 'Cabin'], dtype='object')

In [19]:
print(ds_encoded.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Sex_male          bool
Embarked_Q        bool
Embarked_S        bool
dtype: object

In [20]:
print("Original Shape :", ds.shape)
print("After dropna() :", ds_drop.shape)
print("After fillna() :", ds_fill.shape)

Original Shape : (418, 12)
After dropna() : (87, 12)
After fillna() : (418, 12)

In [21]:
print(ds_encoded.head())

   PassengerId  Survived  Pclass  \
0          892         0       2
1          893         1       2
2          894         0       1
3          895         0       2
4          896         1       2

                                           Name   Age  SibSp  Parch   Ticket  \
0                              Kelly, Mr. James  34.5      0      0   330911
1              Wilkes, Mrs. James (Ellen Needs)  47.0      1      0   363272
2                     Myles, Mr. Thomas Francis  62.0      0      0   240276
3                              Wirz, Mr. Albert  27.0      0      0   315154
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  22.0      1      1  3101298

      Fare Cabin  Sex_male  Embarked_Q  Embarked_S
0   7.8292   NaN      True        True       False
1   7.0000   NaN     False       False        True
2   9.6875   NaN      True        True       False
3   8.6625   NaN      True       False        True
4  12.2875   NaN     False       False        True